apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'mailhog:1025'
      smtp_from: 'alertmanager@example.com'
      smtp_require_tls: false

    route:
      group_by: ['alertname']   # 👈 Added this line
      receiver: 'mailhog-receiver'

    receivers:
    - name: 'mailhog-receiver'
      email_configs:
      - to: 'test@example.com'
        send_resolved: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.27.0
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yaml"
          - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: alertmanager
