apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: LoadBalancer   # 👈 Exposes Grafana via AWS ELB
  ports:
    - port: 3000       # external port
      targetPort: 3000 # Grafana container port
      protocol: TCP
  selector:
    app: grafana
