apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-generator
spec:
  schedule: "*/1 * * * *"  # runs every 1 minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: log-generator
            image: curlimages/curl:8.2.1
            command: ["curl", "-s", "http://log-monitor-service:8000/generate-log"]
          restartPolicy: OnFailure
