apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-monitor-deployment
  namespace: monitoring
  labels:
    app: log-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-monitor
  template:
    metadata:
      labels:
        app: log-monitor
    spec:
      containers:
        - name: log-monitor
          # Placeholder image, replaced by CI/CD pipeline during deploy
          image: nginx:alpine
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: log-monitor-service
  namespace: monitoring
spec:
  selector:
    app: log-monitor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
